name: DEVKING_RELEASE_ONTAG
on:
  workflow_dispatch:  
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message == 'TAG' }}
    steps:
    - uses: actions/checkout@v2
    - run: npm -v
    - run: npm ci
      continue-on-error: true
    - run: node --check ./app.js